require 'rails/generators'
require 'rails/generators/active_record'
require 'rails/generators/active_record/model/model_generator'
require 'rails/generators/active_record/migration/migration_generator'
require 'modular_migration/active_record/generators/model_generator'
require 'modular_migration/active_record/generators/migration_generator'
